import './globals.css'
import { Providers } from './providers'
import Menu from './menu'

export const metadata = {
  title: 'UI Research',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    // <html lang='ko' className='dark'>
    <html lang='ko'>
      <body>
        <Providers>
          <div className='container'>
            <Menu/>
            {children}
          </div>
        </Providers>
      </body>
    </html>
  )
}
