import "./globals.css"
import { Providers } from "./providers"
import Header from "./header"

export const metadata = {
  title: "UI Research",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <html lang="ko">
      <body>
        <Providers>
          <div>
            <Header/>
            {children}
          </div>
        </Providers>
      </body>
    </html>
  )
}
