import './globals.css'
import { Providers } from './providers'

export const metadata = {
  title: 'UI Research',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    // <html lang='ko' className='dark'>
    <html lang='ko'>
      <body>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  )
}
